#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: indy-node
  description: The server portion of a distributed ledger purpose-built for decentralized identity.
  homepage: https://wiki.hyperledger.org/display/indy
  default_branch: master
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
