#!/bin/bash

# Automatically added from template:
if which py3compile >/dev/null 2>&1; then
	py3compile -O -p {package_name} /usr/local/lib/python3.8/dist-packages/
fi

# End automatically added section
