#! /usr/bin/env python3

from plenum.common.test_network_setup import TestNetworkSetup

from sovrin_common.config_util import getConfig
from sovrin_common.txn_util import getTxnOrderedFields

config = getConfig()
portsStart = 9700
nodeParamsFileName = 'sovrin.env'


if __name__ == "__main__":
    TestNetworkSetup.bootstrapTestNodes(config, portsStart, nodeParamsFileName,
                                        getTxnOrderedFields())


# Usages:
# generate_sovrin_pool_transactions --nodes=1 --clients=1 --nodeNum=1
# generate_sovrin_pool_transactions --nodes=4 --clients=1 --nodeNum=1 --envName=live
# generate_sovrin_pool_transactions --nodes=4 --clients=1 --nodeNum=1
# --envName=live --appendToLedgers
