---
- name: Check that required variables are specified
  assert:
    that:
      - lookup('vars', item, default='')
    msg: "{{ lookup('vars', item, default='undefined')|string }}"
  loop:
    - indy_node_build_dir
    - indy_node_channel
    - indy_node_ver
    - indy_plenum_ver
    - python_indy_crypto_ver
    - libindy_crypto_ver
    - network_name
    - indy_node_pool_dir_name
    - indy_node_pool_genesis_txns_name
    - indy_node_pool_genesis_txns_path

# TODO move the following three tasks (HTTPS, sovrin key and sovrin repos)
#      into separate role
- name: Install HTTPS support for apt
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    update_cache: true
  become: true

- name: Add sovrin key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3B75B82CF342D9FB
  become: true

- name: Add sovrin repositories
  apt_repository:
    repo: "deb https://repo.sovrin.org/deb xenial {{ indy_node_channel }}"
    state: present
  become: true

- name: Install indy node
  apt:
    name:
      - "indy-node={{ indy_node_ver }}"
      - "indy-plenum={{ indy_plenum_ver }}"
      - "libindy-crypto={{ libindy_crypto_ver }}"
      - "python3-indy-crypto={{ python_indy_crypto_ver }}"
    update_cache: true
  become: true

- name: Enable node service
  service:
    name: indy-node
    enabled: true
  become: true

- name: Configuration tasks
  include_tasks: configure.yml
  when: indy_node_configuration
