---
- name: Ensure inventory doesn't exists
  file:
    path: "{{ inventory_dir }}"
    state: absent

- name: Destroy public key
  ec2_key:
    name: "{{ aws_keyname }}"
    state: absent

- name: Destroy AWS security group
  ec2_group:
    name: "{{ aws_group }}"
    region: "{{ aws_region }}"
    state: absent
