#! /usr/bin/env python3

from plenum.common.test_network_setup import TestNetworkSetup

from indy_common.config_util import getConfig
from indy_common.txn_util import getTxnOrderedFields

config = getConfig()
portsStart = 9700
nodeParamsFileName = 'indy.env'


if __name__ == "__main__":
    TestNetworkSetup.bootstrapTestNodes(config, portsStart, nodeParamsFileName,
                                        getTxnOrderedFields())


# Usages:
# generate_indy_pool_transactions --nodes=1 --clients=1 --nodeNum=1 --network=live
# generate_indy_pool_transactions --nodes=4 --clients=1 --nodeNum=1 --network=live
# generate_indy_pool_transactions --nodes=4 --clients=1 --nodeNum=1 --network=live
