#! /usr/bin/env python3

from plenum.common.test_network_setup import TestNetworkSetup

from indy_common.config_util import getConfig
from indy_common.config_helper import ConfigHelper, NodeConfigHelper
from indy_common.txn_util import getTxnOrderedFields
import logging


portsStart = 9700
nodeParamsFileName = 'indy.env'


if __name__ == "__main__":
    logger = logging.getLogger()
    logger.disabled = True
    TestNetworkSetup.bootstrapTestNodes(getConfig(), portsStart, nodeParamsFileName,
                                        getTxnOrderedFields(), ConfigHelper, NodeConfigHelper)


# Usages:
# generate_indy_pool_transactions --nodes=1 --clients=1 --nodeNum=1 --network=live
# generate_indy_pool_transactions --nodes=4 --clients=1 --nodeNum=1 --network=live
# generate_indy_pool_transactions --nodes=4 --clients=1 --nodeNum=1 --network=live
