#! /usr/bin/env python3

import os
import argparse

from plenum.common.keygen_utils import init_bls_keys
from plenum.common.script_helper import buildKeepDirIfNotExists

from indy_common.config_util import getConfig

config = getConfig()

key_dir = os.path.join(os.path.expanduser(config.baseDir), config.NETWORK_NAME)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate BLS keys for a node "
                    "by taking the node's name and a seed")

    parser.add_argument('--name', required=True, help='node name')
    parser.add_argument('--seed', required=False, type=str,
                        help='seeds for keypair')

    args = parser.parse_args()

    return args.name, args.seed


def generate_and_store_bls_keys(node_name, seed):
    try:
        init_bls_keys(baseDir=key_dir, node_name=node_name, seed=seed)
    except Exception as ex:
        print(ex)
        exit()


if __name__ == "__main__":
    buildKeepDirIfNotExists(key_dir)
    node_name, seed = parse_args()
    init_bls_keys(key_dir, node_name, seed)
