#! /usr/bin/env python3
#   Copyright 2017 Sovrin Foundation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

import sys


from indy_node.utils.node_runner import run_node
from indy_common.config_util import getConfig

config = getConfig()


if __name__ == "__main__":
    if len(sys.argv) < 4:
        raise Exception("Provide name and 2 port numbers for running the node "
                        "and client stacks")
    
    self_name = sys.argv[1]
    run_node(config, self_name, int(sys.argv[2]), int(sys.argv[3]))
