---
- name: Check that required variables are specified
  assert:
    that:
      - lookup('vars', item, default='')
    msg: "{{ lookup('vars', item, default='undefined')|string }}"
  loop:
    - indy_cli_build_dir
    - indy_cli_channel
    - indy_cli_ver
    - indy_cli_pool_name
    - indy_cli_pool_dir_name
    - indy_cli_pool_genesis_txns_name
    - indy_cli_pool_genesis_txns_path_local
    - indy_cli_pool_genesis_txns_path_remote

- name: Install indy sdk repo
  import_role:
    name: indy_repo
  vars:
    indy_repo_sdk_channels: "{{ indy_cli_channel }}"

- name: Install indy cli
  apt:
    name:
      - "libindy{{ ('=' ~ indy_cli_libindy_ver) if indy_cli_libindy_ver else '' }}"
      - "indy-cli={{ indy_cli_ver }}"
    update_cache: true
  become: true

- name: Install plugins
  import_role:
    name: plugins

- name: Configuration tasks
  include_tasks: configure.yml
  when: indy_cli_configuration
